//
//  RepositoryListPresenter.swift
//  githubSearchApp
//
//  Created by wjLee-PC on 2021/01/26.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RepositoryListPresentationLogic
{
  func presentSomething(response: RepositoryList.Fetch.Response)
}

class RepositoryListPresenter: RepositoryListPresentationLogic
{
  weak var viewController: RepositoryListDisplayLogic?
  
  // MARK: Do something
    //do some business data handling
  func presentSomething(response: RepositoryList.Fetch.Response)
  {
    let displayedRepositories = response
        .repositories
        .map{ RepositoryList.Fetch.DisplayedRepository(id: $0.id,
                                                 fullName: $0.fullName,
                                                 description: $0.description,
                                                 stargazersCount: $0.stargazersCount,
                                                 htmlUrl: $0.htmlUrl)
    }
    let viewmodel = RepositoryList.Fetch.ViewModel(displayedRepository: displayedRepositories)
    viewController?.displaySomething(viewModel: viewmodel)
  }
}
