//
//  RepositoryListModels.swift
//  githubSearchApp
//
//  Created by wjLee-PC on 2021/01/26.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RepositoryList
{
  // MARK: Use cases
  
  enum Fetch
  {
    struct DisplayedRepository
    {
        var id: Int
        var fullName: String
        var description: String?
        var stargazersCount: Int
        var htmlUrl: String
    }
    
    struct Request
    {
        let query:String
    }
    struct Response
    {
        let repositories:[Repository]
    }
    struct ViewModel
    {
     
        var displayedRepository: [DisplayedRepository]
    }
  }
}
